# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
# reading the dataset excel format.
dataset = pd.read_excel('Folds5x2_pp.xlsx')
# Extracting all the features 
X = dataset.iloc[:, :-1].values
# Extracting the target variable
y = dataset.iloc[:, -1].values

In [ ]:
#taking a look at features from the dataset
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
#taking a look at target variable
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
#Splitting the dataset into train and test with  4:1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

We can add any number of layers with any number of neurons or nodes. There is no fixed-procedure to get the values of them. It is the job of practitioner to experiment and get the best model. 

**Note:** Keras is included in Tensorflow 2.0 and higher versions.

**PS** : *Neurons individually cannot do much but layers of them combined together possess super-power. Just like an ant cannot do much but colony of them can build an anthill.*

### Adding the input layer and the first hidden layer

In [ ]:
# the first hidden layer with 6 neurons or nodes with rectifier activation function. 'relu' is the code for it.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
# adding another hidden layer with 6 neurons or nodes with rectifier activation function.
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
#finally, adding the output layer with only one node.
#Note here , I didnt provided activation kwarg coz for regression we donot need to 
#provide activation at the output coz output is continuous.(Basically thats what regression means)
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
#compiling the neural network means configuring it with some defaults
#to get optimal weights, optimization is necessary, I used 'adam' optimiser here.
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
#this part is favourite. Fitting the model with training set.
# i did batch learing with batch_size =32, and epochs =100

# we can play with those kwargs
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 980us/step - loss: 280667.1291
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 213304.8748
Epoch 3/100
240/240 [==============================] - 0s 992us/step - loss: 201079.9926
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 110795.2393
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 512.6503
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 429.1268
Epoch 7/100
240/240 [==============================] - 0s 996us/step - loss: 421.4852
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 403.6434
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 399.6967
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 384.6446
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 373.7554
Epoch 12/100
240/240 [==============================] - 

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
#just setting the precision of 2 for display
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.18 431.23]
 [462.23 460.01]
 [465.73 461.14]
 ...
 [472.96 473.26]
 [439.77 438.  ]
 [458.98 463.28]]


**Evaluating our deep learning model.**


In [34]:
from sklearn.metrics import mean_squared_error,r2_score

#Used regression score and mean square error as two metrics for evaluation
# basically, r2_square close to 1 is a best model.
print('Regression score function reuslt : ', r2_score(y_pred,y_test))
print('mse : ', mean_squared_error(y_pred,y_test)  )


Regression score function reuslt :  0.911016088566643
mse :  24.564055257436344
